"""Conservative, evidence-led OCR quality analysis; confidence alone is not risk.

No dictionary heuristic is used: abbreviations, equations and specialist CJK
terminology are legitimate text. Unknown visual corruption remains diagnostic.
"""

import re
import unicodedata

AI_MARKERS = re.compile(
    r"\bAI[ -]generated\b|\bgenerated by\s+(?:AI|ChatGPT|Midjourney|Stable Diffusion)\b"
    r"|\bmade with AI\b|\b(?:ChatGPT|Midjourney|Stable Diffusion)\b|人工智能生成|AI生成",
    re.I,
)


def analyze_text(text, confidence=1.0):
    chars = [c for c in text if not c.isspace()]
    length = len(chars)
    replacement = sum(c == "\ufffd" for c in chars) / max(length, 1)
    boxes = sum(c in "□▯◻" for c in chars) / max(length, 1)
    controls = sum(unicodedata.category(c) in ("Cc", "Cs") for c in chars) / max(
        length, 1
    )
    signals = []
    if replacement >= 0.1 and chars.count("\ufffd") >= 2:
        signals.append("重复替换字符")
    if boxes >= 0.2 and sum(c in "□▯◻" for c in chars) >= 3:
        signals.append("连续缺字框")
    if controls >= 0.1:
        signals.append("异常控制字符")
    if re.search(r"(?:\ufffd|[□▯◻]|\ufffd\?){3,}", text):
        signals.append("连续损坏字符")
    return {
        "ocr_confidence": float(confidence),
        "replacement_char_ratio": replacement,
        "box_char_ratio": boxes,
        "invalid_char_ratio": controls,
        "character_validity": 1 - min(1, replacement + boxes + controls),
        "text_like_region": bool(length),
        "state": "REVIEW" if signals else "NORMAL",
        "signals": signals,
        "language_coherence": "未用词典推断；专业术语不判乱码",
    }
